### ISSUE TITLE
Problema com inicialização

### ISSUE THREAD

**Issue by AnibalDuarte** [danielbarion/JBlueHeart-Source#19]
Em diversas ocasiões que tento iniciar o servidor ele para nessa parte:

![image](https://user-images.githubusercontent.com/3143872/55406474-8fc09700-5532-11e9-804f-abe741128105.png)

Isso acontece quase sempre quando tento dar um restart. Quando acontece tenho que reiniciar o servidor inteiro (o VPS) para resolver.

Minha infraestrutura está na DigitalOcean, são duas máquinas (uma para o DB e outra para o servidor)

- Banco de dados está em uma máquina na mesma região da máquina do servidor.
- A conexão entre eles é pela rede interna da DigitalOcean, e o ping entre elas não passa de 5ms
- O Loginserver está rodando localmente
- O GameServer está configurado com -Xmx4G 
- A AuctionHouse está desativada e não há itens listados nela

Configurações do DBServer:
- Ubuntu Linux 18.04.2 x64
- 2 vCores, 4GB RAM, 160GB SSD
- MySQL 5.7.25-0ubuntu0.18.04.2

Configurações do servidor:
- Ubuntu Linux 18.04.2 x64
- 4 vCores, 8GB RAM, 160GB SSD
- Java JRE 1.8.0_201-b09

Nota: não foi instalado mais absolutamente nada em nenhuma das máquinas, apenas o Java na do Gameserver e o MySQL na máquina de Banco de Dados.

**Comment by danielbarion** [comment]
Configurações excelentes!

Eu dei uma olhada na print e baseado nas informações que forneceu, a solução é essa:

Código atual:
```
// Auction House Manager
AuctionHouseManager.getInstance();
```
Código novo:
```
if (Config.'nomeDaVariável') {
    // Auction House Manager
    AuctionHouseManager.getInstance();
}
```

https://github.com/danielbarion/JBlueHeart-Source/blob/master/L2J_SunriseProject_Core/java/l2r/gameserver/GameServer.java#L417

A classe está sendo instanciada mesmo se estiver desabilitada, o que não deveria acontecer, se você ver o padrão do gameserver, tem vários mods com validação se ele está habilitado ou não antes de instanciar a classe.

A auction house não fui eu que implementei...

Faça essa mudança e teste, vou ficar aguardando o feedback ;)

**Comment by AnibalDuarte** [comment]
A principio agora ele não inicia mais a instância.

Eu estou tendo alguns travamentos em restarts do servidor nessa configuração, então adicionei mais uns _log.info para analisar onde exatamente ocorrem os travamentos.

**Comment by danielbarion** [comment]
Ele não inicia mais a instancia.. Mas resolveu, certo ? (já era esperado ele não instanciar mesmo esse mod se ele estiver desabilitado).

Hum, belê!

**Comment by AnibalDuarte** [comment]
Estou instalando uma VM com as mesmas características localmente pra testar a inicialização do servidor (mas em vez de duas máquinas separadas tudo vai ser instalado em uma só). 

Se eu não conseguir replicar o erro vou testar com um banco de dados remoto.

**Comment by AnibalDuarte** [comment]
Rotina de testes:

Banco local: iniciei o servidor, reiniciei ele 30x e em nenhuma delas tive problema, tudo foi muito rápido.

Banco remoto (na internet): a inicialização demorou em diversas ocasiões, travando sem retornar nenhum log de erro em algumas delas.


Próxima bateria de testes: vou colocar uma VM na mesma rede com as mesmas configurações que a VM do servidor, mas com as configurações de Banco de Dados para usar o máximo possível do hardware e testar.

**Comment by danielbarion** [comment]
Que comportamento estranho, será que pode ser a conexão com o banco que está com ping alto, assim encavala a inicialização das instancias e trava ?

**Comment by AnibalDuarte** [comment]
Eu não acredito que seja isso, porque o ping entre as máquinas na DigitalOcean é de menos de 5ms.

Eu forcei as mesmas configurações que eu uso no DC (estava usando as padrão do serverpack) e depois de dez tentativas em duas ocasiões com o DB instalado em uma VM paralela o erro ocorreu.

Imaginando que seja mais uma questão de performance de servidor eu reconfigurei o MySQL na máquina de DB (que estava com as configurações padrão) com uma otimização pra tirar o máximo possível da performance do servidor com o s4GB de RAM que ele tem. 

Aparentemente o problema foi resolvido e tempo de carregamento do servidor também está consideravelmente mais rápido, tendo reduzido de aproximadamente 100s pra menos de 60s.

Para registro, anexo o arquivo de configuração.
[mysqld.cnf.txt](https://github.com/danielbarion/JBlueHeart-Source/files/3043537/mysqld.cnf.txt)

Nota: o GameServer está agora com maxConnections=2000 , e como terão 2 GSs no mesmo sevidor de banco de dados o max_connections do MySQL ficou em 5.000 na configuração. Antes estava em 100 conexões no servidor e 500 no MySQL.

Outras fontes de dados que dependem do DB (como o Website) não mostraram melhoria considerável, mas todas elas estão fora da DigitalOcean, rodam muito menos queryes e usam menos volumes de dados que o servidor, por isso não esperava um resultado diferente.

Com isso estou fechando aqui. Publiquei também o update que desativa a AuctionHouse completamente.
